export type Product = {
  id: number;
  slug: string;
  title: string;
  price: number; // MXN
  category: string;
  image: string;
  idealPara: string;
  incluye: string;
  modalidad: string;
  duracion: string;
  resumen: string;
};

export const products: Record<"es" | "en", Product[]> = {
  es: [
    {
      id: 1,
      slug: "preparacion-inicial",
      title: "Preparación Inicial",
      price: 320,
      category: "Bases",
      image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Talentos que comienzan su trayecto de crecimiento corporativo.",
      incluye: "DIAGNÓSTICO INICIAL, RUTA DE APRENDIZAJE Y GUÍA DE ARRANQUE.",
      modalidad: "100% digital con plataforma de recursos.",
      duracion: "120 minutos.",
      resumen: "Encuentro introductorio diseñado para trazar metas, detectar áreas de oportunidad y estructurar un esquema de avance directo y aplicable.",
    },
    {
      id: 2,
      slug: "planeacion-estrategica",
      title: "Planeación Estratégica",
      price: 590,
      category: "Visión Estratégica",
      image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Directivos enfocados en sincronizar el propósito, las metas y la operación diaria.",
      incluye: "MODELOS DE PLANEACIÓN, OKRs Y TABLERO DE INDICADORES.",
      modalidad: "Virtual con sesiones en vivo y formatos de trabajo.",
      duracion: "4 horas efectivas.",
      resumen: "Elabora un mapa de acción robusto que enlace tu visión de negocio con métricas cuantificables al interior de la empresa.",
    },
    {
      id: 3,
      slug: "desarrollo-y-organizacion",
      title: "Desarrollo y Organización",
      price: 700,
      category: "Administración",
      image: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Encargados de articular células de trabajo y sistemas de rendimiento superior.",
      incluye: "DISEÑO ORGANIZACIONAL, ROLES, PROCESOS Y CULTURA.",
      modalidad: "Online interactivo con análisis de casos.",
      duracion: "5 horas de inmersión.",
      resumen: "Asimila las mejores prácticas para estructurar grupos de trabajo, fijar procedimientos nítidos y consolidar una identidad volcada a las metas.",
    },
    {
      id: 4,
      slug: "curso-de-innovacion-y-creatividad-empresarial",
      title: "Curso de Innovación y Creatividad Empresarial",
      price: 1200,
      category: "Inventiva",
      image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Grupos de trabajo dispuestos a idear propuestas y alternativas de alto valor.",
      incluye: "DESIGN THINKING, IDEACIÓN Y PROTOTIPADO RÁPIDO.",
      modalidad: "Sesiones digitales con dinámicas de co-creación.",
      duracion: "6 horas.",
      resumen: "Estimula la mente creativa de tu personal mediante técnicas vanguardistas enfocadas en resolver obstáculos verídicos del mercado.",
    },
    {
      id: 5,
      slug: "curso-de-estrategias-de-negocios-modulo-basico",
      title: "Curso de Estrategias de Negocios Módulo Básico",
      price: 1500,
      category: "Visión Estratégica",
      image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Fundadores y gerentes que requieren cimientos tácticos sólidos.",
      incluye: "MODELO DE NEGOCIO, ANÁLISIS DE MERCADO Y VENTAJA COMPETITIVA.",
      modalidad: "Transmisión en red con recursos anexos.",
      duracion: "6 horas.",
      resumen: "Comprende los pilares de la planeación para ejecutar resoluciones corporativas fundamentadas y viables a largo plazo.",
    },
    {
      id: 6,
      slug: "taller-de-comunicacion-efectiva-en-equipos-de-trabajo",
      title: "Taller de Comunicación Efectiva en Equipos de Trabajo",
      price: 1800,
      category: "Competencias",
      image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Células operativas que desean interactuar con nitidez y seguridad.",
      incluye: "ESCUCHA ACTIVA, FEEDBACK Y COMUNICACIÓN ASERTIVA.",
      modalidad: "Taller digital con prácticas en tiempo real.",
      duracion: "6 horas.",
      resumen: "Mejora los canales de diálogo corporativo, minimizando roces y uniendo fuerzas para incrementar el éxito conjunto.",
    },
    {
      id: 7,
      slug: "taller-de-manejo-de-equipos-multidisciplinarios",
      title: "Taller de Manejo de Equipos Multidisciplinarios",
      price: 1980,
      category: "Dirección",
      image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Cabezas de proyecto interactuando con áreas y perfiles heterogéneos.",
      incluye: "COORDINACIÓN, ROLES, CONFLICTOS Y ALINEACIÓN DE METAS.",
      modalidad: "Aula en línea apoyada en situaciones reales.",
      duracion: "7 horas.",
      resumen: "Administra la pluralidad de capacidades en tu grupo de trabajo para hacer de la variedad un auténtico rasgo diferenciador.",
    },
    {
      id: 8,
      slug: "curso-de-gestion-de-recursos-humanos-nivel-basico",
      title: "Curso de Gestión de Recursos Humanos – Nivel Básico",
      price: 2100,
      category: "Talento Humano",
      image: "https://images.unsplash.com/photo-1573497620053-ea5300f94f21?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Especialistas dando sus primeros pasos en la administración de personal.",
      incluye: "ATRACCIÓN, DESARROLLO, EVALUACIÓN Y CLIMA LABORAL.",
      modalidad: "Plataforma en línea con formatos para descargar.",
      duracion: "8 horas completas.",
      resumen: "Domina los principios para captar, formar y fidelizar colaboradores, edificando entornos de trabajo prósperos y eficientes.",
    },
    {
      id: 9,
      slug: "curso-de-marketing-digital-para-negocios",
      title: "Curso de Marketing Digital para Negocios",
      price: 2500,
      category: "Comercialización",
      image: "https://images.unsplash.com/photo-1557838923-2985c318be48?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Compañías decididas a expandir su huella en el ecosistema digital.",
      incluye: "ESTRATEGIA, CONTENIDOS, EMBUDOS Y MÉTRICAS.",
      modalidad: "Virtual con resolución de casos de estudio.",
      duracion: "8 horas.",
      resumen: "Estructura un plan de medios cibernéticos capaz de captar prospectos, detonar interés y evaluar rendimientos con precisión.",
    },
    {
      id: 10,
      slug: "curso-de-gestion-del-cambio-organizacional",
      title: "Curso de Gestión del Cambio Organizacional",
      price: 2800,
      category: "Administración",
      image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Conductores de procesos de evolución dentro de sus corporaciones.",
      incluye: "MODELOS DE CAMBIO, COMUNICACIÓN Y ADOPCIÓN.",
      modalidad: "Sesiones en la web con tutoría especializada.",
      duracion: "8 horas.",
      resumen: "Encabeza transiciones empresariales metódicamente, mitigando la reticencia y agilizando la integración de nuevas prácticas.",
    },
    {
      id: 11,
      slug: "curso-de-finanzas-para-no-financieros",
      title: "Curso de Finanzas para No Financieros",
      price: 3200,
      category: "Economía",
      image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Supervisores con injerencia en los resultados monetarios del negocio.",
      incluye: "ESTADOS FINANCIEROS, FLUJO DE EFECTIVO Y PRESUPUESTO.",
      modalidad: "Módulos virtuales apoyados en simulaciones financieras.",
      duracion: "8 horas.",
      resumen: "Asimila los reportes y cifras esenciales de la firma para dictar resoluciones acertadas sin necesidad de ser un perito contable.",
    },
    {
      id: 12,
      slug: "curso-de-liderazgo-para-mandos-medios",
      title: "Curso de Liderazgo para Mandos Medios",
      price: 3450,
      category: "Dirección",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Coordinadores y jefaturas en vías de potenciar su capacidad de mando.",
      incluye: "ESTILOS DE LIDERAZGO, MOTIVACIÓN DE EQUIPOS Y TOMA DE DECISIONES.",
      modalidad: "Conexión remota con conferencias web y guías anexas.",
      duracion: "8 horas.",
      resumen: "Forja una dirección despierta y certera, logrando estimular, orientar y multiplicar el rendimiento de tus colaboradores.",
    },
    {
      id: 13,
      slug: "diplomado-en-estrategias-de-negocios-nivel-intermedio",
      title: "Diplomado en Estrategias de Negocios – Nivel Intermedio",
      price: 8400,
      category: "Certificación",
      image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Talentos en busca de una inmersión táctica profunda y multidisciplinaria.",
      incluye: "ESTRATEGIA, FINANZAS, LIDERAZGO Y EJECUCIÓN APLICADA.",
      modalidad: "Programa virtual extenso con asesoría de proyecto.",
      duracion: "40 horas intensivas.",
      resumen: "Un circuito educativo robusto que fusiona dirección, análisis financiero y destreza operativa para catapultar tu trayectoria.",
    },
  ],
  en: [
    {
      id: 1,
      slug: "preparacion-inicial",
      title: "Initial Preparation",
      price: 320,
      category: "Basics",
      image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Talents starting their journey of corporate growth.",
      incluye: "INITIAL DIAGNOSIS, LEARNING PATH AND KICK-OFF GUIDE.",
      modalidad: "100% digital with resource platform.",
      duracion: "120 minutes.",
      resumen: "Introductory meeting designed to map out goals, detect areas of opportunity, and structure a direct and applicable advancement scheme.",
    },
    {
      id: 2,
      slug: "planeacion-estrategica",
      title: "Strategic Planning",
      price: 590,
      category: "Strategic Vision",
      image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Directors focused on synchronizing purpose, goals, and daily operation.",
      incluye: "PLANNING MODELS, OKRs AND INDICATOR DASHBOARD.",
      modalidad: "Virtual with live sessions and work formats.",
      duracion: "4 effective hours.",
      resumen: "Develop a robust action map linking your business vision with quantifiable metrics within the company.",
    },
    {
      id: 3,
      slug: "desarrollo-y-organizacion",
      title: "Development and Organization",
      price: 700,
      category: "Administration",
      image: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Managers in charge of articulating work cells and top-performance systems.",
      incluye: "ORGANIZATIONAL DESIGN, ROLES, PROCESSES AND CULTURE.",
      modalidad: "Interactive online with case analysis.",
      duracion: "5 hours of immersion.",
      resumen: "Assimilate best practices to structure work groups, establish clear procedures, and consolidate an identity focused on goals.",
    },
    {
      id: 4,
      slug: "curso-de-innovacion-y-creatividad-empresarial",
      title: "Business Innovation and Creativity Course",
      price: 1200,
      category: "Inventiveness",
      image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Work groups willing to devise high-value proposals and alternatives.",
      incluye: "DESIGN THINKING, IDEATION AND RAPID PROTOTYPING.",
      modalidad: "Digital sessions with co-creation dynamics.",
      duracion: "6 hours.",
      resumen: "Stimulate your staff's creative mind through cutting-edge techniques focused on solving true market obstacles.",
    },
    {
      id: 5,
      slug: "curso-de-estrategias-de-negocios-modulo-basico",
      title: "Business Strategies Course Basic Module",
      price: 1500,
      category: "Strategic Vision",
      image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Founders and managers requiring solid tactical foundations.",
      incluye: "BUSINESS MODEL, MARKET ANALYSIS AND COMPETITIVE ADVANTAGE.",
      modalidad: "Network transmission with attached resources.",
      duracion: "6 hours.",
      resumen: "Understand the pillars of planning to execute sound and long-term viable corporate resolutions.",
    },
    {
      id: 6,
      slug: "taller-de-comunicacion-efectiva-en-equipos-de-trabajo",
      title: "Effective Communication in Work Teams Workshop",
      price: 1800,
      category: "Competencies",
      image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Operational cells aiming to interact with clarity and confidence.",
      incluye: "ACTIVE LISTENING, FEEDBACK AND ASSERTIVE COMMUNICATION.",
      modalidad: "Digital workshop with real-time practices.",
      duracion: "6 hours.",
      resumen: "Improve corporate dialogue channels, minimizing friction and joining forces to increase joint success.",
    },
    {
      id: 7,
      slug: "taller-de-manejo-de-equipos-multidisciplinarios",
      title: "Multidisciplinary Team Management Workshop",
      price: 1980,
      category: "Direction",
      image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Project heads interacting with heterogeneous areas and profiles.",
      incluye: "COORDINATION, ROLES, CONFLICTS AND GOAL ALIGNMENT.",
      modalidad: "Online classroom supported by real situations.",
      duracion: "7 hours.",
      resumen: "Manage the plurality of capabilities in your work group to turn variety into a genuine distinguishing feature.",
    },
    {
      id: 8,
      slug: "curso-de-gestion-de-recursos-humanos-nivel-basico",
      title: "Human Resources Management Course – Basic Level",
      price: 2100,
      category: "Human Talent",
      image: "https://images.unsplash.com/photo-1573497620053-ea5300f94f21?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Specialists taking their first steps in personnel administration.",
      incluye: "ATTRACTION, DEVELOPMENT, EVALUATION AND WORK CLIMATE.",
      modalidad: "Online platform with downloadable formats.",
      duracion: "8 full hours.",
      resumen: "Master the principles to attract, train, and retain collaborators, building prosperous and efficient work environments.",
    },
    {
      id: 9,
      slug: "curso-de-marketing-digital-para-negocios",
      title: "Digital Marketing for Business Course",
      price: 2500,
      category: "Commercialization",
      image: "https://images.unsplash.com/photo-1557838923-2985c318be48?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Companies determined to expand their footprint in the digital ecosystem.",
      incluye: "STRATEGY, CONTENT, FUNNELS AND METRICS.",
      modalidad: "Virtual with case study resolution.",
      duracion: "8 hours.",
      resumen: "Structure a cyber media plan capable of capturing prospects, triggering interest, and accurately evaluating performance.",
    },
    {
      id: 10,
      slug: "curso-de-gestion-del-cambio-organizacional",
      title: "Organizational Change Management Course",
      price: 2800,
      category: "Administration",
      image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Drivers of evolution processes within their corporations.",
      incluye: "CHANGE MODELS, COMMUNICATION AND ADOPTION.",
      modalidad: "Web sessions with specialized tutoring.",
      duracion: "8 hours.",
      resumen: "Spearhead business transitions methodically, mitigating reluctance and expediting the integration of new practices.",
    },
    {
      id: 11,
      slug: "curso-de-finanzas-para-no-financieros",
      title: "Finance for Non-Financial Professionals Course",
      price: 3200,
      category: "Economics",
      image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Supervisors with influence over the monetary outcomes of the business.",
      incluye: "FINANCIAL STATEMENTS, CASH FLOW AND BUDGET.",
      modalidad: "Virtual modules supported by financial simulations.",
      duracion: "8 hours.",
      resumen: "Assimilate the essential reports and figures of the firm to dictate sound resolutions without needing to be an accounting expert.",
    },
    {
      id: 12,
      slug: "curso-de-liderazgo-para-mandos-medios",
      title: "Leadership for Middle Management Course",
      price: 3450,
      category: "Direction",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Coordinators and managers looking to boost their command capabilities.",
      incluye: "LEADERSHIP STYLES, TEAM MOTIVATION AND DECISION MAKING.",
      modalidad: "Remote connection with web conferences and attached guides.",
      duracion: "8 hours.",
      resumen: "Forge an alert and accurate direction, succeeding in stimulating, guiding, and multiplying the performance of your collaborators.",
    },
    {
      id: 13,
      slug: "diplomado-en-estrategias-de-negocios-nivel-intermedio",
      title: "Business Strategies Diploma – Intermediate Level",
      price: 8400,
      category: "Certification",
      image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=1200&auto=format&fit=crop",
      idealPara: "Talents seeking a deep and multidisciplinary tactical immersion.",
      incluye: "STRATEGY, FINANCE, LEADERSHIP AND APPLIED EXECUTION.",
      modalidad: "Extensive virtual program with project advising.",
      duracion: "40 intensive hours.",
      resumen: "A robust educational circuit merging direction, financial analysis, and operational dexterity to catapult your career.",
    },
  ],
};

export function getProduct(slug: string, lang: "es" | "en"): Product | undefined {
  return products[lang].find((p) => p.slug === slug);
}

export const IVA_RATE = 0.16;

export function formatMXN(value: number): string {
  return new Intl.NumberFormat("es-MX", {
    style: "currency",
    currency: "MXN",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })
    .format(value)
    .replace("$", "MXN$");
}